name: Setup site branch

on:
  push:
    branches:
      - main
      - code

jobs:
  setup-site-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code branch
      uses: actions/checkout@v3
      with:
        ref: code

    - name: Setup npm
      run: npm i
    
    - name: Set up Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Clone 'main' branch into directory
      run: |
        git clone https://github.com/${{ github.repository }} site
        rm -rf site/.git

    - name: Create site
        npm run create-site

    - name: Commit the changes
      run: |
        cd site
        git init
        git remote add origin https://github.com/${{ github.repository }}
        git add -A
        git commit -m "Updated Site"
        git push origin site --force