name: Setup site branch

on:
  push:
    branches:
      - main

jobs:
  setup-site-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code branch
      uses: actions/checkout@v3
      with:
        ref: code
    
    - name: Use Deno v2
      uses: denoland/setup-deno@v2
    
    - name: Set up Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        echo ---
        pwd
        echo ---
        ls

    - name: Clone 'main' branch into directory
      run: |
        git clone https://github.com/${{ github.repository }} site
        rm -rf site/.git
        echo ---
        pwd
        echo ---
        ls

    - name: Setup npm
      run: |
        npm i
        echo ---
        pwd
        echo ---
        ls

    - name: Create site
      run: |
        npm run create-site
        echo ---
        pwd
        echo ---
        ls

    - name: Commit the changes
      run: |
        cd site
        git init
        git remote add origin https://github.com/${{ github.repository }}
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add -A
        git commit -m "Updated Site"
        git push origin site --force
        echo ---
        pwd
        echo ---
        ls